### ISSUE TITLE
주문 조회 검색 조건 값 필드 수정

### ISSUE THREAD

**Issue by wolveshowl** [TeamProject-Farmer/back-end#238]
## Description
주문 조회 검색 조건 값 필드 수정

## Todo
- [x] 주문 조회 시 주문상태 관련 필드가 Null로 값을 전송할 떄, 오류가 발생하는 부분 해결
- [x] 전체 주문 처리상태의 필드값을 추가하여, 전체 주문 처리 상태로 조회 할 때 모든 주문 상태의 주문 데이터들을 불러오게 함.
- [x] EndDate(종료일)의 값이 null일때, 400에러를 클라이언트에 전달하여 사후 검증 처리
