### ISSUE TITLE
적립금 적용 후 사후처리 검증 추가, 주문자 회원 정보조회 오류 수정

### ISSUE THREAD

**Issue by wolveshowl** [TeamProject-Farmer/back-end#260]
## Description
적립금 적용 후 사후처리 검증 추가, 주문자 회원 정보조회 오류 수정

## Todo
- [x] 기존 적립금 할인 적용 시, 회원이 보유한 적립금보다 많은 금액을 차감하여 음수로 데이터가 저장됨을 확인하고,
- [x] 검증 절차를 통해서 차감 할 수 있도록 수정.
- [x] 주문/결제 시 주문자명으로 회원을 조회할때에 Bad Request가 발생하는 것을 확인함.
- [x] 주문자명은 수령자와 비슷한 개념으로 같은 회원이 다른 주문자명으로 주문 할 수 있어야함으로,
- [x] 엑세스 토큰 정보를 통해 로그인 회원의 정보를 조회해서 주문을 완료한다.
