### ISSUE TITLE
주문번호로 주문 조회 시 데이터 오류 수정

### ISSUE THREAD

**Issue by wolveshowl** [TeamProject-Farmer/back-end#275]
## Description
주문번호로 주문 조회 시 데이터 오류 수정

## Todo
- [x] 주문번호로 주문을 조회할때 기본 배송지로 저장한 배송지가 조회되지 않는것을 확인함.
- [x] 주문 로직에 있는 더티 체킹 로직에 오류가 있는 것으로 확인하고 수정함.
- [x] 엑세스 토큰 만료기한 수정
